config/routes.rb
Surfy::Application.routes.draw do

  devise_for :users
  root :to => "profiles#index"

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :profiles
  resources :surf_sessions
  get 'surf_spots' => "surf_spots#index"
  get 'surf_spots/:id' => "surf_spots#show"

  get 'landing' => "landing#index"

  post 'surf_sessions/update_sessions_in_display' => 'surf_sessions#update_sessions_in_display'

  

end

app/models/profile.rb
class Profile < ActiveRecord::Base

	belongs_to :user
end

app/models/surf_session.rb
class SurfSession < ActiveRecord::Base

	belongs_to :user
	has_many :waves
	belongs_to :surf_spot

	def date
		self.created_at.strftime("%d/%m/%Y")
	end

	def random_generation

	end
	
end

app/models/surf_spot.rb
class SurfSpot < ActiveRecord::Base

	has_many :surf_sessions
	has_many :users, through: :surf_sessions
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  has_one :profile
  has_many :surf_sessions
  has_many :waves, through: :surf_sessions


	def full_name
  	return "#{first_name} #{last_name}"
  end

  def gravitar_url
      gravitar = Digest::MD5.hexdigest(email)
      "http://www.gravatar.com/avatar/#{gravitar}.jpg"
  end     

  private
  def user_params
  	unless params[:user].blank?
  		  params.require(:user).permit(:email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :profile_name)
  	end
  end

end

app/models/wave.rb
class Wave < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_devise_params, if: :devise_controller?

  protect_from_forgery with: :exception


  def happy
  	render text: "happy"
  end

  def sad
  	render text: "sad"
  end




  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :first_name, :last_name)
    end
  end




  protected
 
  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def index
		@users = User.all
	end

	def show 
		@user = User.find(params[:id])
		@update_time = Time.new
	end

end

app/controllers/surf_sessions_controller.rb
class SurfSessionsController < ApplicationController

	def show
		respond_to do |format|
			@surf_session = SurfSession.find(params[:id])
			format.js {}
		end
	end

	def new
		@surf_session = SurfSession.new
	end

	def create


		@surf_session = SurfSession.new(surf_sessions_params)
		@surf_session.surf_spot_id = @surf_session.surf_spot_id || SurfSpot.first(:offset => rand(SurfSpot.count)).id
		@surf_session.user_id = current_user.id 
		@surf_session.location = @surf_session.location || 'Polzeath'

		respond_to do |format|
			if @surf_session.save
				format.html { redirect_to root_path, notice: params}
				format.js {}
			else
				format.html { render :new, alert: 'failed to save'}
				format.js {}
			end
		end

	end

	def edit
		@surf_session = SurfSession.find(params[:id])

	end

	def update
		@surf_session = SurfSession.find(params[:id])

	end

	def destroy
		@surf_session = SurfSession.find(params[:id])
		@outfit.delete
	end

	def update_sessions_in_display

		@time_stamp = (params[:surf_session][:time_stamp]).to_i;
		@user = params[:surf_session][:profile_user];
		@time_now = Time.new.to_i;
		@sessions = SurfSession.where(user_id: @user).where("created_at > ?", Time.at(@time_stamp) );
		
		
		respond_to do |format|
			format.json { render json: {sessions: @sessions, timeNow: @time_now }};
		end


	end


	private
	def surf_sessions_params
		params.require(:surf_session).permit(:location)
	end

end

app/controllers/surf_spots_controller.rb
class SurfSpotsController < ApplicationController

	def index
		@spots = SurfSpot.all
	end

	def show
		@spot = SurfSpot.find(params[:id])
	end

	def new
	end

	def create
	end

	def edit
		@spot = SurfSpot.find(params[:id])
	end

	def update
		@spot = SurfSpot.find(params[:id])
	end

	def delete
	end

	private
	def surf_spot_params

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authenticate_user!

	def index
		@users = User.all

		respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
	end

	def show
		@user = User.find(params[:id])

		respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
	end

end

app/controllers/waves_controller.rb
class WavesController < ApplicationController

	def show
		@wave = Wave.find(:id)
	end

	def new
		@wave = Wave.new
	end

	def create
		@wave = Wave.new(wave_param)

		if @wave.save
			happy
		else
			sad
		end

	end

	def edit
		@wave = Wave.find(:id)
	end

	def update
		@wave = Wave.find(:id)

		if @wave.update_attributes(wave_params)
			happy
		else
			sad
		end

	end

	def destroy
		@wave = Wave.find(:id)
	end

	private
	def waves_params
		params.require(:wave).permit(:description)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper

	# Accessable devise log-in & sign-up
	def resource_name
		:user
	end

	def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
   #-----------------------------------
	
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/surf_sessions_helper.rb
module SurfSessionsHelper
end

app/helpers/surf_spots_helper.rb
module SurfSpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/waves_helper.rb
module WavesHelper
end

app/views/landing/index.html.erb
<div class="container">

	<div class="panel" id="bot_button" style="text-align: center; margin: 20px 250px; background: rgba(100,255,100,0.6);">
		<p id="starty">Start Bot</p>
		<p id="stoppy" style="display: none;">Stop Bot</p>
	</div>

	<div class="panel " style="text-align: center;">

		<% all_user_ids = [] %>
		<% User.all.each do |user| %>
			<p id="user<%=user.id%>"><%=user.full_name%></p>
			<% all_user_ids << user.id %>

		<% end %>

		<% all_spots = [] %>
		<% SurfSpot.all.each do |spot| %>
			<% all_spots << spot.id %>

		<% end %>

	</div>

</div>

<script type="text/javascript">

	var all_users = <%= all_user_ids %>;

	var scriptInterval = false;

	function randomSpotDetails(){

		var spot_id = all_spots[Math.floor(Math.random() * all_spots.length)];

		






		
		return { id: spot_id, entry: spot_id};
	}

	function startSession(userID){

		var sessionStart = Math.floor(Math.random() * 50000);

		setTimeout(function(){

			var sessionDuration = Math.floor((Math.random() * 20000)+ 5000);
			var target_user_selector = '#user'+  userID;
			console.log('sesh start -' + sessionDuration);
			
			$(target_user_selector).css('color','rgba(255,140,60,1)');

				var interval = setInterval(function(){
					console.log('gps blip for user '+ userID);
				},1000)

			setTimeout(function(){

				$(target_user_selector).css('color','white');
				console.log('sesh end');

				clearInterval(interval);

			}, sessionDuration);

		}, sessionStart);
	}

	function startBot(){

		scriptInterval = setInterval(function(){

			var usersSurfing =[];
			var usersNotSurfing = [];

			for (var i = all_users.length - 1; i >= 0; i--) {
				n = Math.random();

				if (n > 0.7) {
					usersSurfing.push(all_users[i]);
				};
			};

			jQuery.grep(all_users, function(el) {
	    	if (jQuery.inArray(el, usersSurfing) == -1) usersNotSurfing.push(el);
			});

			console.log('surfing this hour ' + usersSurfing);
			console.log('not surfing ' + usersNotSurfing);

			for (var i = usersSurfing.length - 1; i >= 0; i--) {
				startSession(usersSurfing[i]);

			};
		}, 60000);
	}

	function stopBot(){
		if (scriptInterval){
			clearInterval(scriptInterval);
		}
	}

	$('#starty').on("click", function(){
		$(this).parent().children("p").toggle();	
			startBot();

	})

	$('#stoppy').on("click", function(){
		$(this).parent().children("p").toggle();
			stopBot();
	})


</script>

app/views/layouts/_footer.html.erb
<div class="footer_fix"></div>

<div class="footer">
		<hr>
		<h4 class="centered">&#169; <%= Time.now.year %>, SomeApp</h4>
</div>

app/views/layouts/_header.html.erb
<div class="header_wrap" id="header">

		<div class="header">
			<div class="container" id="navigation">
				<a href="<%= root_path %>"><div class="logo"><h2>InstaWavifyifybookagram</h2></div></a>
				<div class="navbar">
					<ul class="nav login_out">

							<% if user_signed_in? %>
								<li><%= link_to (image_tag (current_user.gravitar_url), :class => "header_gravitar"), edit_user_registration_path %>
								</li>
								<li><%= link_to "Sign Out", logout_path %>
								</li>
								<!-- <li><a href="#"><img class="options_bar" src="images/option_bars.png"></a></li> -->
							<% else !user_signed_in? %>
								<li><%= link_to "Sign Up!", register_path %>
								<li><%= link_to "Sign in", login_path %>
							<% end %>

						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
<!-- </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SomeApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>



	<%= render partial: 'layouts/header' %>
	
<div class="page_wrap">

		<div class="flash container">
			<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
		</div>

	<%= yield %>


	<%= render partial: 'layouts/footer' %>
</div>
</body>
</html>

app/views/profiles/index.html.erb
<div class="container">

	<% @users.each do |user| %>

		<div class="panel"> <%= link_to user.full_name, profile_path(user.id) %> </div>

	<% end %>

</div>

app/views/profiles/show.html.erb
<div class="container">

	<div class="profile_panel">

		<img class="arrow" src="/images/down_arrow.png">
		<img class="arrow" src="/images/up_arrow.png" style="display: none;">

		<div class="profile_summary">
			<%= (image_tag (@user.gravitar_url), :class => "profile_gravitar") %><!--

		--><div class="quick_bio">
					<h2>
						<%= @user.full_name %>
						<% if @user.pro %> <span class="pro">Pro</span><% end %>
					</h2>
					<p><%= @user.tagline %></p>
			</div>

		</div>
		<div class="full_profile">
			This is the content for the full profile<br>
			This is the content for the full profile<br>
			This is the content for the full profile<br>
			This is the content for the full profile<br>
			This is the content for the full profile<br>
		</div>
	</div>

	<div class="sessions_container">

		<% @user.surf_sessions.each do |session| %>

			<div class="session_panel" data-session="<%= session.id %>">

				<div class="session_summary">

					<img class="arrow" src="/images/down_arrow.png">
				<img class="arrow" src="/images/up_arrow.png" style="display: none;">

					<h3 class="title"><%= session.surf_spot.location %> <span class="date"><%= session.date %></span></h3>
					<p>Session length: 1h 48m  Fastest Wave: 16kmph Longest Ride: 21s </p>
				</div>
				<div class="full_session">
					<div class="session_data">

					<div class="map_holder"><%= (image_tag ("/images/" + session.surf_spot.image_url), :class => "map_img") %>

						<div class="marker_on"></div>
						<div class="marker_on"></div>
						<div class="marker_on"></div>
						<div class="marker_on"></div>
						<div class="marker_on"></div>




					</div>
					<div class="waves_holder">

						<div class="wave_detail"><span class="date">15:04:23 </span>- Length: 11.3s Speed: 9km/h</div>

						<div class="wave_detail"><span class="date">15:13:01 </span>- Length: 17.8s Speed: 14.2.7km/h</div>

						<div class="wave_detail"><span class="date">15:29:09 </span>- Length: 14.0s Speed: 12km/h</div>

						<div class="wave_detail"><span class="date">15:44:42 </span>- Length: 9.2s Speed: 11.8km/h</div>

						<div class="wave_detail"><span class="date">15:56:33 </span>- Length: 18.1s Speed: 10.3km/h</div>

						<div class="wave_detail"><span class="date">16:11:51 </span>- Length: 12.6s Speed: 16km/h</div>

						<div class="wave_detail"><span class="date">15:24:39 </span>- Length: 21.1s Speed: 9km/h</div>

						<div class="wave_detail"><span class="date">15:35:21 </span>- Length: 17.0s Speed: 12km/h</div>

						<div class="wave_detail"><span class="date">15:43:10 </span>- Length: 16.2s Speed: 11.4km/h</div>
						
					</div>
					
					<div class="wave_chart">

						<img src="/images/wavechart.png">

					</div>

					</div>
				</div>
			</div>

		<% end %>

	</div>

	<div class="container">
		<a id="clicky" href="#"><div class='panel'>Add New</div></a>
	</div>

</div>

<!---  ==============  -->

<script type="text/javascript">

	var updateTime = <%= @update_time.to_i %>;

	var user = <%= @user.id %>;

	$('.full_profile').height(200);

	$('#clicky').on("click", function(event){
			
			posty();
			return false;

		}
	);

	$('.profile_panel').on("click", function(event){
			
			showMore('.full_profile');

			var targetImg = $(this).children('.arrow');

			targetImg.toggle();

		});

	$('.session_summary').on("click", function(event){
			
		var target = $(this).parent().children('.full_session');
		var targetImg = $(this).children('.arrow');

		targetImg.toggle();


			showMore(target);
			return false;

		}
	);

	function posty(){
		
		function randomSpot(){
			var locations = ['Praa Sands','Polzeath','Harlyn','Porthleven','Perranporth','Crantock','South Fistral','The Cribbar','North Fistral','Lusty Glaze','Mawgan Porth']

			var random_index = Math.floor(Math.random() * locations.length);

			return locations[random_index];
		}

		$.ajax({
			url: "/surf_sessions", 
			type: "POST",
			datatype : 'text json',
			data:{ submit: true, 
						 surf_session: {location: 'beef' },
						 commit: 'Create Surf session',
						 action: 'create',
						 controller: 'surf_sessions' },
			success: function(response){
			}

		});
	}

	function listSessionsInView(){

		var list = [];

		$('.sessions_container')
								.find('.session_panel')
								.each( 
									function(){ list.push($(this).data("session"))}
										);	

		return list;
	}

	function updateSessions(){

		$.ajax({
			url: "/surf_sessions/update_sessions_in_display", 
			type: "POST",
			datatype : 'json',
			data:{ 
						 surf_session: { profile_user: user, time_stamp: updateTime },
						 commit: 'Update Surf sessions',
						 action: 'update_sessions_in_display',
						 controller: 'surf_sessions' },
			success: function(response){

				if (response.sessions.length > 0) {

					var i;
					for (i = 0; i < response.sessions.length; ++i) {
						var sesh = response.sessions[i];

						var sessionDate = new Date(sesh.created_at);
						var formattedDate = sessionDate.getDate()+"/"+(sessionDate.getMonth()+1)+"/"+sessionDate.getFullYear()

						var newHTML = "<div class='session_panel' data-session=" + sesh.id +">" +
													"<h3 class='title'>"+ sesh.location +" <span class='date'>"+
													 formattedDate + "</span></h3>" +
													"<p>Session length: X  Fastest Wave: X  Longest Ride: X </p></div>";

						$('.sessions_container').append(newHTML);

					}
				}	

				updateTime = response.timeNow

			}
		});
	}

	function showMore(target) {


	$(target).toggle(200);

	
	}

	setInterval(function(){updateSessions();}, 15000);

</script>

app/views/profiles/show.js.erb
alert('yo');

app/views/surf_sessions/_form.html.erb
	<%= form_for(@surf_session) do |f| %>
		<div class="field">
			<%= f.label :location %>
			<%= f.text_field :location %>
		</div>
		<div class="action">
			<%= f.submit %>
		</div>
	<% end %>

app/views/surf_sessions/create.js.erb
alert('saved!')

function help() {
	alert('help function');	
}

app/views/surf_sessions/new.html.erb
<div class="container">
	<%= render partial: 'form' %>
</div>

app/views/surf_sessions/show.js.erb
alert('showy show');

app/views/surf_spots/_spot_card.html.erb
<div class="spot_card">
	<%= spot.id %>



</div>

app/views/surf_spots/index.html.erb
<div class="container">

	<% @spots.each do |spot| %>


	<div class="spot_panel" data-session="<%= spot.id %>">

				<div class="session_summary">

					<img class="arrow" src="/images/down_arrow.png">
					<img class="arrow" src="/images/up_arrow.png" style="display: none;">

					<h3 class="title"><%= spot.location %></h3>
					<p>Surf report summary </p>
				</div>
				<div class="full_spot">
				</div>
	</div>

	<% end %>

</div>

app/views/surf_spots/show.html.erb
<div class="container">

	<div class="panel">
			<h2><%= @spot.location %></h2>
	</div>

</div>